FROM python:3.9

COPY requirements.txt requirements.txt
COPY .aws /root/.aws
COPY app /app

RUN pip3 install -r requirements.txt

CMD ["celery", "-A", "app.tasks", "worker", "--loglevel", "DEBUG", "--logfile", "log_celery.txt"]
